### ISSUE TITLE
LTI 1.3 Platform implementation

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1149]
This is a meta-issue to collect tasks needed to complete LTI 1.3 platform implementation. The below checkboxes indicate the status at branch [PasiSa/lti-platform](https://github.com/PasiSa/a-plus/tree/lti-platform), not merged yet to master.

TODO list of intended features planned at this time:

- [X] [OpenID Connect handshake and resource link launch](https://github.com/apluslms/a-plus/issues/1150)
- [X] Bearer token permission class
- [X] LineItem and Score interfaces according to [LTI Assignment and Grades Specification](http://www.imsglobal.org/spec/lti-ags/v2p0)
- [x] Finalize database models (separate subclasses for Legacy LTI and LTI 1.3) for LTIExercise and LTIService, cleanup migration scripts. Also, verify that migration scripts do not break existing external service configurations in DB.
- [X] Bearer token management (remove expired tokens from DB, Django admin interface for Bearer token table)
- [x] Anonymous mode (e.g. MathWorks requires this)

Following bugs/problems need to be solved yet:

- [x] Trailing slashes still don't work perfectly. LTI does not want URLs to end with trailing slash, but our current Django deployment does. The current solution attempt works with LTI, but when user tries to access other pages without trailing slash, at least some of them are not accessible anymore (at least the admin view has problems). The expectation was that Django appends the Slash to these URLs automatically (APPEND_SLASH defaults to True), but for some reason this does not happen.
- [x] Side menu does work after recent changes
- [x] Edit assignment view does not work with LTI1p3 exercises

Finally: 

- [x] Code cleanup (e.g.: translations, comments, module structure, check through all TODO comments)
- [x] Clean up git history

There will be small additions to LTI-related RST-tool configurations, so small updates are also needed to rst-tools and gitmanager parameter validation.

Also needed (but not blocking completion of this a-plus issue):
- aplus-manual page covering LTI 1.3

Useful references:

- [LTI v1.3 Core Specification](https://www.imsglobal.org/spec/lti/v1p3)
- [1EdTech Security Framework](https://www.imsglobal.org/spec/security/v1p0/)
- [Launching an LTI 1.3 Resource Link using OpenID Connect Third Party Login](https://andyfmiller.com/2018/12/28/launching-an-lti-1-3-resource-link-using-openid-connect-third-party-login/) (a blog post that might be useful)
- [OAuthLib documentation](https://oauthlib.readthedocs.io/en/latest/index.html)
