### ISSUE TITLE
Random images (gravatar) for anonymous users

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#418]
- [ ] Serve random gravatar like images (do not link to gravatar, as we don't have good fake emails for that etc)
- [ ] Use images in A+ in anonymous mode
- [ ] Share link to the image in LTI launch for anonymous services

**Comment by Mankro** [comment]
Closing because we will remove user profile images (gravatar) from all users in https://github.com/apluslms/a-plus/issues/698.
