### ISSUE TITLE
LTI: add missing LTI tool consumer parameters

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#429]
All tool consumer fields:

- [ ] `tool_consumer_info_product_family_code`, recomended, **missing**
- [ ] `tool_consumer_info_version`, recommended, **missing**
- [x] `tool_consumer_instance_guid`, strongly recommended, exists, fixed in ##576
- [x] `tool_consumer_instance_name`, recommended, exists
- [x] `tool_consumer_instance_description`, optional, ~missing~ added in #548
- [x] `tool_consumer_instance_url`, optional, ~missing~ added in #548 
- [ ] `tool_consumer_instance_contact_email`, recomended, **missing**

LTI spec https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide

**Comment by Mankro** [comment]
LTI parameters are defined in this file in the code: https://github.com/apluslms/a-plus/blob/master/external_services/lti.py

**Comment by Mankro** [comment]
This issue was made for the old LTI 1.0 and 1.1 versions. I close this now since we have added support for LTI Platform v1.3 and its parameters are not identical to the old version.
LTI Platform v1.3 was added in #1175.
