### ISSUE TITLE
Pages load too slowly; efficiency boost needed

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#450]
- [x] It takes a very long time (even more than a minute) for A+ to show the "Edit course details" page, at least in Chrome. This seems to be related to way the "Assistants" section is populated. The page is slow because the "add assistants" section in the edit course details form includes all users from the A+ database in hidden form fields. Fixing this would require that the form JS could query the server via AJAX. The JS needs to search for users whose names match the input. The real user IDs are also needed.  - addressed in #479
- [ ] The student list page is extremely often (many, many times per day) used by course staff, but 
loads very slowly in large-class courses. Needs an efficiency boost.
- [x] The course points page (aka. the list of student points for the staff). Addressed in #797

**Comment by Mankro** [comment]
The "add assistants" section is fixed with this PR: https://github.com/apluslms/a-plus/pull/479

The student list (participants) page is a different case.

**Comment by jparta** [comment]
The student points page is being worked on. RxJS was selected as the main tool.
[Aalto Wiki](https://wiki.aalto.fi/pages/viewpage.action?pageId=168090459
)
[Fork](https://github.com/jparta/a-plus/tree/staff-results)

**Comment by Mankro** [comment]
Just to clarify, the original issue mentions the student list (participants) page in A+, while the student points (all results) page mentioned by jparta is a different page.

**Comment by raphendyr** [comment]
> Just to clarify, the original issue mentions the student list (participants) page in A+, while the student points (all results) page mentioned by jparta is a different page.

Yes, but if it works well with browser caching, we could use it for the participants page too. Or merge the views so it would be a kind of a dashboard to course staff about students.

**Comment by etanttila** [comment]
> Just to clarify, the original issue mentions the student list (participants) page in A+, while the student points (all results) page mentioned by jparta is a different page.

Since the pages are different, is there a separate issue for the course points page or is it part of this issue as well?

**Comment by raphendyr** [comment]
Change to meta issue and added points page to be tragged.

**Comment by Mankro** [comment]
@skulonen Nice, good ideas! 

I can't actually see how the `_profiles.html` template is included in the participants page. The participants view uses this template:
https://github.com/apluslms/a-plus/blob/660f98d0906b05a925fca64c6f2c3906497fc8f6/course/templates/course/staff/participants.html#L150
https://github.com/apluslms/a-plus/blob/660f98d0906b05a925fca64c6f2c3906497fc8f6/course/staff_views.py#L23-L44

Participants.html renders the table in JavaScript. The JSON dump of the data is added to the html by the view.
https://github.com/apluslms/a-plus/blob/master/assets/js/participants.js
The JS also uses the package django-colortag:
https://github.com/apluslms/django-colortag/tree/master/django_colortag/static

----------------------------------------------------------------------------------------

Concerning the optimatization of database queries:
What about the cache? `CachedStudent` contains taggings.
https://github.com/apluslms/a-plus/blob/660f98d0906b05a925fca64c6f2c3906497fc8f6/course/cache/students.py#L15-L30

**Comment by skulonen** [comment]
@Mankro 

> I can't actually see how the _profiles.html template is included in the participants page.

Oh, looks like I was dumb yesterday. Indeed, the participants page doesn't use the `profiles` template tag, and in fact it loads very quickly after the first load, during which the students cache is populated. I guess I accidentally looked at the submission list or some other template that uses the `profiles` tag yesterday...

But nevertheless, the performance bottleneck related to the user tags still exists in the `profiles` tag. It just doesn't affect the participants page.

I came across this issue when I tried to use the `profiles` tag to add links to the submitter field of the deviation list, which made it tremendously slow.

**Comment by Mankro** [comment]
OK, the `profiles` template tag could also be improved. However, since the participants page already uses `CachedStudent` for the taggings, then why is the page loading too slowly in large courses like O1 that also use a lot of tags? Is the slowness actually caused by the frontend JavaScript code that creates the tag buttons on each student row in the table?

**Comment by skulonen** [comment]
It doesn't seem slow at all to me (200 students and 2 tags, each student tagged with both of them). Sure, the initial load before the cache is populated is slow, but after that the page loads in less than a second. Maybe the issue is that the cache is invalidated too easily? Looks like every time you add/update/delete a tag (*tag*, not *tagging*), the cache is invalidated for every student in the course, which leads to the next load being slower.

**Comment by Mankro** [comment]
O1 2021 has 1050 students, each student has 2-6 taggings and the course instance defines 54 tags.

Loading the participants page may take a few seconds on repeated page refreshes, thus cache should be active. You can also see on the page how the JS creates the table first and adds missing buttons half a second later.

**Comment by skulonen** [comment]
Ohh, we're talking about a load time of a few seconds here? I was expecting the participants page to be **very** slow, like the deviation list which loaded in a couple of minutes before the recent optimizations.

**Comment by PasiSa** [comment]
Can we now close this? And open more specific follow-up issues if needed.

**Comment by Mankro** [comment]
The issue with the `profiles` template tag above (https://github.com/apluslms/a-plus/issues/450#issuecomment-995872265) was fixed with the `prefetch_tags` method in v1.13:
https://github.com/apluslms/a-plus/blob/b1490fd151cba471d14aaa6a69d80ee9c13568ec/userprofile/models.py#L23-L41

**Comment by Mankro** [comment]
Closing this issue. The participants page was moved to a new issue #982.
