### ISSUE TITLE
Upgrade the CSS framework

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#584]
Because bootstrap 3 classes are basically part of A+ assessment protocol, we can't just replaces it with another CSS framework. Instead, we need to first fix our first problem, which was not having prefixes for bootstrap 3 classes.

Second huge problem is, that we can't have bootstrap 3 and 4 classes at the same time. It might be enough, that we leave existing classes as is and just prefix the new framework. However, I think it would still be beneficial to cleanup the old classes first, so we clearly know, where they are used.

One challenge is that may of the classes are used in the feedback html stored in the database and there is no methods to migrate those. Thus, before we drop the old classes, we need to wait so long that none of the classes are in the database anymore.

Possible migration plan:

- [ ] Start using SASS for A+ and replace CDN bootstrap 3 with a locally build version.
- [ ] Create a second set of bootstrap 3 classes with a prefix (e.g. `bs3-` or `aplus1-` to match the assessment tool protocol)
- [ ] Migrate all assessment tools to use these prefixed classes (will take probably 1-2 years)

  - [ ] Update assessment protocol documentation
  - [ ] [MOOC-Grader](https://github.com/apluslms/mooc-grader)
  - [ ] [MOOC-Jutut](https://github.com/aalto-letech/mooc-jutut)
  - [ ] [Rubyric](https://github.com/aalto-letech/rubyric) (check if it uses any bootstrap classes)
  - [ ] [ACOS](https://github.com/acos-server/acos-server) (check if it uses bootstrap classes at all)
  - [ ] [Peer Review Platform](https://github.com/piehei/prplatform/)
  - [ ] [Grading Helper](https://github.com/eliisav/gradinghelper/)
  - TODO: other systems?

- [ ] Wait for a long time for all courses to rotate, so there isn't any old classes in the database (e.g. 3 years from last assessment tool update)
- [ ] Drop the default class names
- [ ] Add bs4 prefixed classes (assessment tools can start using bs4 cllasses now)

Adapt this plan, when better solution are drafted. For example, if bootstrap 3 and 4 can coexist better than I assume, then we can start using bs4- classes earlier (adapt the plan then).

Any case, starting to use SASS would be priority 1 to start this long process.

**Comment by Mankro** [comment]
Is it necessary to start anything in this issue during the summer 2020? This is a huge task. Once we have new long-term employees (hopefully in the autumn), they could deal with these matters from start to finish.

**Comment by raphendyr** [comment]
I think a simple solution would be prebuilding a bootstrap 3 with the prefix and adding those to the repo/instances in Januaru 2021.  With the next year, we might be able to upgrade most of the assessment services to use the prefixed names. Then maybe in 2025 or such we could drop the current classes. (unless we don't need to wait that part).

I think we could try to add two prebuild bootstarp 3 files to the repo (with and without prefix) and start adding support for the prefix classes (I think some templates in A+ must be edited). This wouldn't require updating the build pipeline with SASS, but would allow us to start the long process.

**Comment by raphendyr** [comment]
Before that, we must evaluate if the plan sounds valid, or if there are clear problems. It also might be too careful.

**Comment by mtthwhggns** [comment]
It _may_ also be worth evaluating whether Bootstrap is still the best tool for the job. The range of CSS Frameworks has changes a lot since it was chosen, and it's possible that alternatives could work even better for the platform-level components, which would allow us to keep Bootstrap 3 available for the dependencies.
