### ISSUE TITLE
The identity proofing policy changes in the Haka identity federation

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#789]
## Announcement from HAKA

The identity proofing policy changes in the Haka identity federation

Currently all users in Haka are identified by higher education institutions by means of a document issued by the authority or equivalent when issuing user IDs.

At the beginning of 2022, the identity proofing policy of the Haka identity federation will change to match the REFEDS Assurence Framework (RAF) [1] definition, allowing home organizations to implement identity proofing assurance in three levels of increasing requirements. Particularly, the change allows a lower level identity proofing, for example based on email.

The change will allow universities and services to offer their services more flexibly, for example to foreign students and researchers. The increase in new user groups may necessitate the service providers to review their own policies and practices, in order to distinguish the less identity proofed users from other users in the services, if necessary.

The Haka service agreement obliges service providers to monitor the legitimate use of the service. If the service requires a certain level of identity proofing, the service should start requesting the eduPersonAssurance attribute as defined by the RAF specification and begin checking the attribute values to enforce the service access policy, if any. The attributes requested by the service are set in the resource registry [2].

Before the beginning of 2022, home organizations will release the values of the eduPersonAssurance attribute according to the current identity federation policy [3]. In this way, the services can adapt to the change before the actual policy update, if needed.

***All services providers must assess the impact of the change on their services.***
If the lower identity proofing level has no effect on the service, the situation will remain unchanged. If there is a need for changes, the service must enforce the necessary access control based on the new attribute values.

For additional information, please contact haka at csc.fi. Further announcements will be sent later.

[ 1 ] https://wiki.refeds.org/display/ASS/REFEDS+Assurance+Framework+ver+1.0

[ 2 ] https://rr.funet.fi/rr

[ 3 ] https://wiki.eduuni.fi/x/qIegAQ

---------------------------------------------------------------------------------

HAKA login is related to https://github.com/apluslms/a-plus/issues/788.

Internal ticket for EDIT: https://rt.cs.aalto.fi/Ticket/Display.html?id=18381

## TODO

- [ ] determine how this affects A+. Is it a problem that HAKA users might be identified with only email?
- [ ] determine what kind of users might enter A+ with the HAKA login in the future
- [ ] determine how Aalto University and the mainstream platforms respond to this change (MyCourses Moodle)
- [ ] Implement changes in the A+ Shibboleth login if necessary. It should be easy to check some new attribute value.
- [ ] If necessary, request new attributes from HAKA in rr.funet.fi for the production servers (normal and exam environments)

**Comment by PasiSa** [comment]
It is unclear if this affects us. I will check what e.g. MyCourses will do about this. and probably we should take similar actions (if any).

**Comment by PasiSa** [comment]
We concluded last year that this does not cause actions for us, at least for now, and therefore the corresponding issue was closed in Jira then. Therefore I'm closing it here now. Will also remove it from the next milestone, because it really does not belong to the milestone.
