### ISSUE TITLE
Calendar and deadline exports to UI and other systems

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#85]
Rework the deadline / calendar interfaces. A+ should export relevant data to the student and other systems. It's common that the user has a dashboard somewhere ellse, so we should be able to populate the data there, in addition to providing an A+ interface too.

This is now a Meta issue and following subissues could be created to contribute to calendar and deadline data.

- [ ] Ensure iCal export is working. Remember caching
- [ ] Add calendar widget, rendered by JS or by Django. Remember to use caching
- [ ] Export this information to MyCourses, so student can have merged view there
- [ ] Export this information to Salesforce, so students can have merged view there

**Comment by raphendyr** [comment]
Original description, containing ideas for the calendar view / deadline list

> I think current iCal link on sidebar is not good as it can be seen as external link and external links in side bar menu is not good practice (imho).
> 
> Instead I think that there should be page containing list of all upcoming deadlines. Preferable multiple styles of displaying. And on that page there should be filter bar where user could select which courses, which exercises / exercise types should be listed. Next to or some where on display should be link to iCal which would show/download filtered events.
> 
> One display style would be list days one by one and mark what deadliness are on that day.
> 
> Example:
> 
> ```
>  4.2.2013
>  5.2.2013 course foobar: exercise 0 - itroduction
>  6.2.2013
>  7.2.2013
>  8.2.2013
> 
> 11.2.2013 course barbaz: exercise 1 - Using git
> 12.2.2013 course foobar: exercise 1 - The real thing
>           course bazbaz: project demo reservation
> 13.2.2013
> 14.2.2013
> 15.2.2013
> ```

**Comment by Mankro** [comment]
Teachers have requested a calendar export from A+ to Outlook this autumn. It should be possible to subscribe to updates since the course deadlines may be changed.

**Comment by annirytkonen** [comment]
I close this issue, we are going to follow Aalto level practices and if this is one of them, this can be re-opened or new issue created.
